# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geos-extensions"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = "2012-05-23"
  s.description = "Extensions for the GEOS library."
  s.email = "code@zoocasa.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/models/geos/geometry_column.rb",
    "app/models/geos/spatial_ref_sys.rb",
    "geos-extensions.gemspec",
    "lib/geos-extensions.rb",
    "lib/geos/active_record_extensions.rb",
    "lib/geos/active_record_extensions/connection_adapters/postgresql_adapter.rb",
    "lib/geos/active_record_extensions/spatial_columns.rb",
    "lib/geos/active_record_extensions/spatial_scopes.rb",
    "lib/geos/geos_helper.rb",
    "lib/geos/google_maps.rb",
    "lib/geos/google_maps/api_2.rb",
    "lib/geos/google_maps/api_3.rb",
    "lib/geos/google_maps/polyline_encoder.rb",
    "lib/geos/rails/engine.rb",
    "lib/geos_extensions.rb",
    "lib/tasks/test.rake",
    "test/adapter_tests.rb",
    "test/database.yml",
    "test/fixtures/foo3ds.yml",
    "test/fixtures/foo_geographies.yml",
    "test/fixtures/foos.yml",
    "test/geography_columns_tests.rb",
    "test/geometry_columns_tests.rb",
    "test/google_maps_api_2_tests.rb",
    "test/google_maps_api_3_tests.rb",
    "test/google_maps_polyline_encoder_tests.rb",
    "test/misc_tests.rb",
    "test/reader_tests.rb",
    "test/spatial_scopes_geographies_tests.rb",
    "test/spatial_scopes_tests.rb",
    "test/test_helper.rb",
    "test/writer_tests.rb"
  ]
  s.homepage = "http://github.com/zoocasa/geos-extensions"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Extensions for the GEOS library."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

