# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geos-extensions}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{J Smith}]
  s.date = %q{2011-07-12}
  s.description = %q{Extensions for the GEOS library.}
  s.email = %q{code@zoocasa.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/models/geos/geometry_column.rb",
    "app/models/geos/spatial_ref_sys.rb",
    "geos-extensions.gemspec",
    "lib/geos-extensions.rb",
    "lib/geos/active_record_extensions.rb",
    "lib/geos/active_record_extensions/connection_adapters/postgresql_adapter.rb",
    "lib/geos/active_record_extensions/geometry_columns.rb",
    "lib/geos/active_record_extensions/geospatial_scopes.rb",
    "lib/geos/geos_helper.rb",
    "lib/geos/google_maps.rb",
    "lib/geos/google_maps/api_2.rb",
    "lib/geos/google_maps/api_3.rb",
    "lib/geos/google_maps/polyline_encoder.rb",
    "lib/geos/rails/engine.rb",
    "lib/geos_extensions.rb",
    "lib/tasks/test.rake",
    "test/adapter_test.rb",
    "test/fixtures/foos.yml",
    "test/geometry_columns_test.rb",
    "test/geospatial_scopes_test.rb",
    "test/google_maps_api_2_test.rb",
    "test/google_maps_api_3_test.rb",
    "test/reader_test.rb",
    "test/test_helper.rb",
    "test/writer_test.rb"
  ]
  s.homepage = %q{http://github.com/zoocasa/geos-extensions}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Extensions for the GEOS library.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

