# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zoocasa-geos-extensions}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = %q{2010-11-30}
  s.description = %q{GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology Suite (JTS).}
  s.email = %q{code@zoocasa.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Rakefile",
    "lib/active_record_extensions.rb",
    "lib/active_record_extensions/connection_adapters/postgresql_adapter.rb",
    "lib/active_record_extensions/geometry_columns.rb",
    "lib/active_record_extensions/geospatial_scopes.rb",
    "lib/geos_extensions.rb",
    "lib/geos_helper.rb",
    "lib/google_maps.rb",
    "lib/google_maps/polyline_encoder.rb",
    "test/reader_test.rb",
    "test/test_helper.rb",
    "test/writer_test.rb"
  ]
  s.homepage = %q{http://github.com/zoocasa/geos-extensions}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology Suite (JTS).}
  s.test_files = [
    "test/reader_test.rb",
    "test/test_helper.rb",
    "test/writer_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

